<div class="accent">
	<div class="breadcrumb bac2">
		<p>I'm a breadcrumb! > oh yeah you're here</p></p>
	</div>
	<div class="content bac2">
		<h3>welcome to class!</h3>
		<p>you're so welcome in class</p>
		<div id="css_SwitchHolder">
			<div id="original">
				<img src="img/pc.png" alt="original styles" />
			</div>
			<div id="projector">
				<img src="img/projector.png" alt="projector styles" />
			</div>
		</div>
	</div>
</div>