<a href="#mobile_nav" class="open"></a>
<ul id="mobile_nav">
	<li><a href="index.php" data-target="content/home.inc">home</a></li>
	<li><a href="lectures.inc">lectures</a>
		<ul class="secondary">
			<li><a href="lecture.inc" data-target="content/lectures/01.inc">01</a>
				<ul class="tertiary">
					<li>test</li>
					<li>test</li>
				</ul>
			</li>
		</ul>
	</li>
	<li><a href="#" data-target="content/resources.inc">resources</a></li>
	<li><a href="#" data-target="content/quiz.inc">quiz</a></li>
</ul>