<h2><a href="#mobile_nav" class="open"></a></h2>
<ul id="mobile_nav">
	<li><a href="#">Home</a></li>
	<li><a href="#">lectures</a>
		<ul class="secondary">
			<li>01
				<ul class="tertiary">
					<li>test</li>
					<li>test</li>
				</ul>
			</li>
			<li>02</li>
			<li>03</li>
			<li>04</li>
			<li>05</li>
			<li>06</li>
			<li>07</li>
			<li>08</li>
			<li>09</li>
			<li>10</li>
			<li>11</li>
		</ul>
	</li>
	<li><a href="#">Resources</a></li>
	<li><a href="#">Quiz</a></li>
</ul>