<a href="#mobile_nav" class="open"></a>
<ul id="mobile_nav">
	<h2>comp 1950</h2>
	<li><a href="/comp1950-final/public/index.php">home</a></li>
	<li>lectures
		<ul class="secondary">
			<li><a href="/comp1950-final/public/content/lectures/04.php" data-target="/comp1950-final/public/includes/lectures/04.inc">04</a>
			</li>
		</ul>
	</li>
	<li><a href="/comp1950-final/public/content/resources.php" data-target="/comp1950-final/public/includes/resources.inc">resources</a></li>
	<li><a href="/comp1950-final/public/content/quiz.php" data-target="/comp1950-final/public/includes/quiz.inc">quiz</a></li>
</ul>